# Label Encoding

In [5]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
# Feature
products = ['홈런볼','꼬북칩','허니버터칩','초코파이','초코파이']
# Encoding
l_encoder = LabelEncoder()
l_encoder.fit(products)
labels = l_encoder.transform(products)
# 결과 확인
print('인코딩 변환값 :',labels)
print('\n인코딩 클래스 :',l_encoder.classes_)
print('\n디코딩 원본값 :',l_encoder.inverse_transform([3,0,2,1,1]))

인코딩 변환값 : [3 0 2 1 1]

인코딩 클래스 : ['꼬북칩' '초코파이' '허니버터칩' '홈런볼']

디코딩 원본값 : ['홈런볼' '꼬북칩' '허니버터칩' '초코파이' '초코파이']


# One-Hot Encoding

In [8]:
# One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder
# Numpy
import numpy as np
# 2차원 ndarray 변환
products = np.array(products).reshape(-1,1)
# Encoding
oh_encoder = OneHotEncoder()
oh_encoder.fit(products)
oh_labels = oh_encoder.transform(products)
# 결과 확인
print('One-Hot 인코딩 데이터')
print(oh_labels.toarray())
print('\nOne-Hot 인코딩 데이터 차원')
print(oh_labels.shape)

One-Hot 인코딩 데이터
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]

One-Hot 인코딩 데이터 차원
(5, 4)


# get_dummies()

In [9]:
# Pandas
import pandas as pd
# get_dummies()
df = pd.DataFrame({'products' : ['홈런볼','꼬북칩','허니버터칩','초코파이','초코파이']})
pd.get_dummies(df)

products_꼬북칩  products_초코파이  products_허니버터칩  products_홈런볼
0             0              0               0             1
1             1              0               0             0
2             0              0               1             0
3             0              1               0             0
4             0              1               0             0